{
  "speakers": [
    {
      "id": 1,
      "name": "Dr. Rajesh Kumar",
      "designation": "Professor of Strategic Management",
      "institution": "IIT Delhi",
      "country": "India",
      "area": "Strategic Management & Sustainability",
      "category": "keynote",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Dr. Kumar has over 20 years of experience in strategic management research and consulting, with a focus on sustainable business transformation across emerging markets.",
      "sessionTitle": "Driving Inclusive Sustainability in Indian Enterprises",
      "sessionDate": "21 December 2026",
      "sessionTime": "10:00 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 2,
      "name": "Prof. Sarah Johnson",
      "designation": "Professor of Organizational Behavior",
      "institution": "Harvard Business School",
      "country": "USA",
      "area": "Organizational Behavior & Culture",
      "category": "international",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Prof. Johnson is a renowned expert in organizational psychology and leadership development, advising Fortune 500 companies on culture transformation.",
      "sessionTitle": "Culture as a Driver of Organizational Resilience",
      "sessionDate": "21 December 2026",
      "sessionTime": "11:30 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 3,
      "name": "Dr. Emma Chen",
      "designation": "Associate Professor of Digital Innovation",
      "institution": "Tsinghua University",
      "country": "China",
      "area": "Digital Innovation & Sustainable Computing",
      "category": "international",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Dr. Chen specializes in digital transformation strategies for global enterprises with an emphasis on sustainable and responsible technology adoption.",
      "sessionTitle": "Sustainable Computing: The Next Frontier",
      "sessionDate": "22 December 2026",
      "sessionTime": "9:30 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 4,
      "name": "Prof. Michael Anderson",
      "designation": "Professor of Corporate Finance",
      "institution": "London Business School",
      "country": "UK",
      "area": "Finance, Accounting & Economics",
      "category": "international",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Prof. Anderson has published extensively on corporate finance and investment strategy, with recent work on sustainable finance frameworks.",
      "sessionTitle": "Financing Inclusive Growth: A Global Perspective",
      "sessionDate": "22 December 2026",
      "sessionTime": "2:00 PM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 5,
      "name": "Dr. Priya Sharma",
      "designation": "Associate Professor of Human Resource Management",
      "institution": "Indian Institute of Management, Ahmedabad",
      "country": "India",
      "area": "Future of Work & Human Resource Management",
      "category": "national",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Dr. Sharma is a leading researcher in talent management and workplace diversity, focusing on the future of work in hybrid environments.",
      "sessionTitle": "Reimagining the Future of Work",
      "sessionDate": "21 December 2026",
      "sessionTime": "3:30 PM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 6,
      "name": "Prof. Hassan Al-Rashid",
      "designation": "Professor of International Business",
      "institution": "American University of Sharjah",
      "country": "UAE",
      "area": "Entrepreneurship & Industry Collaboration",
      "category": "international",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Prof. Al-Rashid focuses on cross-cultural management and entrepreneurship ecosystems across the Middle East and South Asia.",
      "sessionTitle": "Building Cross-Border Entrepreneurial Ecosystems",
      "sessionDate": "22 December 2026",
      "sessionTime": "11:00 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 7,
      "name": "Prof. Thandiwe Mokoena",
      "designation": "Professor of Sustainable Business",
      "institution": "Central University of Technology, Free State",
      "country": "South Africa",
      "area": "Sustainability & Responsible Business",
      "category": "keynote",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Prof. Mokoena leads sustainability research at CUT, South Africa, and is a key collaborator in the BRAIN'26 India-South Africa partnership.",
      "sessionTitle": "DISTINCT: A South African Perspective on Inclusive Sustainability",
      "sessionDate": "21 December 2026",
      "sessionTime": "9:00 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    },
    {
      "id": 8,
      "name": "Dr. Anjali Verma",
      "designation": "Assistant Professor of Corporate Governance",
      "institution": "NSUT, New Delhi",
      "country": "India",
      "area": "Corporate Governance & Ethics",
      "category": "national",
      "image": "./images/speakers/speaker-placeholder.jpg",
      "bio": "Dr. Verma researches governance frameworks and ethical compliance in Indian corporations, contributing to BRAIN'26's governance track.",
      "sessionTitle": "Governance for a Sustainable Tomorrow",
      "sessionDate": "22 December 2026",
      "sessionTime": "10:30 AM",
      "linkedin": "#",
      "twitter": "#",
      "website": "#"
    }
  ]
}
